version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    tty: true
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    tty: true
    ports: 
       - "5433:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "todoApi"
      TZ: "Asia/Tokyo"

