/* tslint:disable */
/* eslint-disable */
/**
 * ToDo REST API
 * ToDoアプリのREST API。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    InlineResponse200,
    InlineResponse200FromJSON,
    InlineResponse200ToJSON,
} from '../models';

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * HTTPヘッダに設定するためのCSRFトークンを取得する。 
     * CSRFトークンの取得
     */
    async getCsrfTokenRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<InlineResponse200>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/csrf_token`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse200FromJSON(jsonValue));
    }

    /**
     * HTTPヘッダに設定するためのCSRFトークンを取得する。 
     * CSRFトークンの取得
     */
    async getCsrfToken(initOverrides?: RequestInit): Promise<InlineResponse200> {
        const response = await this.getCsrfTokenRaw(initOverrides);
        return await response.value();
    }

}
